[[actions]]
name = "commit_desc"
lua = '''
jj("desc")
revisions.refresh()
flash("Commit description updated.")
'''

[[bindings]]
key = "ctrl+d"
action = "commit_desc"
scope = "revisions"
desc = "commit desc via lazycommit"
