[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { userLanguages = { gleam = "html", "*.gleam" = "html" }, tailwindCSS = { experimental = { classRegex = [ [ "class\\([\"']([^\"']*)[\"']\\)" ] ] } } }

[[language]]
name = "nix"
language-servers = [ "nixd", "nil" ]
formatter = { command = "nixpkgs-fmt" }
auto-format = true

[[language]]
name = "gleam"
language-servers = [ "gleam", "tailwindcss-ls" ]
auto-format = true

[[language]]
name = "elixir"
language-servers = [ "elixir-ls", "tailwindcss-ls" ]
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "vscode-eslint-language-server" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true
