[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { userLanguages = { gleam = "html", "*.gleam" = "html" }, tailwindCSS = { experimental = { classRegex = [ [ "class\\([\"']([^\"']*)[\"']\\)" ], [ "cn\\(([^)]*)\\)", "[\"'`]([^\"'`]+)[\"'`]" ] ] } } }

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
# format = true # optional
nodePath = ""
# onIgnoredFiles = "off" # optional
# packageManager = "yarn" # optional
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false # optional
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
# codeActionsOnSave = { mode = "all" } # optional
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
experimental = { useFlatConfig = true } ### NEEDED FOR FLAT CONFIG 
problems = { shortenToSingleLine = false }
# workingDirectory = { mode = "auto" } # optional

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "djot"
language-servers = [ "codebook", "tailwindcss-ls" ]

[[language]]
name = "nix"
language-servers = [ "nixd", "nil" ]
formatter = { command = "nixpkgs-fmt" }
auto-format = true

[[language]]
name = "gleam"
language-servers = [ "gleam", "tailwindcss-ls", "codebook" ]
auto-format = true

[[language]]
name = "elixir"
language-servers = [ "elixir-ls", "tailwindcss-ls" ]
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "eslint", "codebook" ]
formatter = { command = 'bunx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "eslint",
  "tailwindcss-ls",
  "codebook"
]
formatter = { command = 'bunx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "eslint",
  "tailwindcss-ls",
  "codebook"
]
formatter = { command = 'bunx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'bunx', args = ["prettier", "--parser", "html"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'bunx', args = ["prettier", "--parser", "css"] }
auto-format = true


[[language]]
name = "json"
formatter = { command = 'bunx', args = ["prettier", "--parser", "json"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = [ "codebook" ]
